server:
  port: 9094
  
security:
  sessions: NEVER

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    warmupnew:
      path: /warmupnew/**
      url: http://localhost:9999
    oauth-server:
      path: /oauth-server/**
      url: http://localhost:9092
      sensitiveHeaders: Authorization 
      
authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
      